
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID DIGIT PLUS MINUS TIMES DIVIDE EQUALS LPAREN RPARENassign : ID EQUALS exprexpr : expr PLUS term\n        | expr MINUS term\n        | term term : term TIMES factor\n        | term DIVIDE factor\n        | factor factor : LPAREN expr RPAREN\n        | ID\n        | number number : number DIGIT\n        | DIGIT '
    
_lr_action_items = {'ID':([0,3,8,11,12,13,14,],[2,4,4,4,4,4,4,]),'$end':([1,4,5,6,7,9,10,16,17,18,19,20,21,],[0,-9,-1,-4,-7,-10,-12,-11,-2,-3,-5,-6,-8,]),'EQUALS':([2,],[3,]),'LPAREN':([3,8,11,12,13,14,],[8,8,8,8,8,8,]),'DIGIT':([3,8,9,10,11,12,13,14,16,],[10,10,16,-12,10,10,10,10,-11,]),'TIMES':([4,6,7,9,10,16,17,18,19,20,21,],[-9,13,-7,-10,-12,-11,13,13,-5,-6,-8,]),'DIVIDE':([4,6,7,9,10,16,17,18,19,20,21,],[-9,14,-7,-10,-12,-11,14,14,-5,-6,-8,]),'PLUS':([4,5,6,7,9,10,15,16,17,18,19,20,21,],[-9,11,-4,-7,-10,-12,11,-11,-2,-3,-5,-6,-8,]),'MINUS':([4,5,6,7,9,10,15,16,17,18,19,20,21,],[-9,12,-4,-7,-10,-12,12,-11,-2,-3,-5,-6,-8,]),'RPAREN':([4,6,7,9,10,15,16,17,18,19,20,21,],[-9,-4,-7,-10,-12,21,-11,-2,-3,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign':([0,],[1,]),'expr':([3,8,],[5,15,]),'term':([3,8,11,12,],[6,6,17,18,]),'factor':([3,8,11,12,13,14,],[7,7,7,7,19,20,]),'number':([3,8,11,12,13,14,],[9,9,9,9,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> ID EQUALS expr','assign',3,'p_assign','TRYHARD22.py',49),
  ('expr -> expr PLUS term','expr',3,'p_expr','TRYHARD22.py',52),
  ('expr -> expr MINUS term','expr',3,'p_expr','TRYHARD22.py',53),
  ('expr -> term','expr',1,'p_expr','TRYHARD22.py',54),
  ('term -> term TIMES factor','term',3,'p_term','TRYHARD22.py',57),
  ('term -> term DIVIDE factor','term',3,'p_term','TRYHARD22.py',58),
  ('term -> factor','term',1,'p_term','TRYHARD22.py',59),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor','TRYHARD22.py',62),
  ('factor -> ID','factor',1,'p_factor','TRYHARD22.py',63),
  ('factor -> number','factor',1,'p_factor','TRYHARD22.py',64),
  ('number -> number DIGIT','number',2,'p_number','TRYHARD22.py',67),
  ('number -> DIGIT','number',1,'p_number','TRYHARD22.py',68),
]
